name: osu-droid
options:
  bundleIdPrefix: com.osudroid
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: ""
    CODE_SIGNING_ALLOWED: "NO"
    CODE_SIGNING_REQUIRED: "NO"
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"

targets:
  osu-droid:
    type: application
    platform: iOS
    sources:
      - path: osu-droid/Sources
      - path: osu-droid/Resources
        optional: true
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.osudroid.app
        INFOPLIST_FILE: osu-droid/Info.plist
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: true
        SWIFT_EMIT_LOC_STRINGS: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          SWIFT_COMPILATION_MODE: wholemodule
    dependencies: []

schemes:
  osu-droid:
    build:
      targets:
        osu-droid: all
    run:
      config: Debug
    archive:
      config: Release
