name: osu-droid
options:
  bundleIdPrefix: com.osudroid
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: ""
    CODE_SIGNING_ALLOWED: "NO"
    CODE_SIGNING_REQUIRED: "NO"
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"

targets:
  osu-droid:
    type: application
    platform: iOS
    sources:
      - path: osu-droid/Sources
        type: group
      - path: osu-droid/Resources
        type: group
        optional: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.osudroid.app
        INFOPLIST_FILE: osu-droid/Info.plist
        SUPPORTED_PLATFORMS: iphoneos iphonesimulator
        SUPPORTS_MACCATALYST: false
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: true
        SWIFT_EMIT_LOC_STRINGS: true
        # Landscape only
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        # Audio background mode
        INFOPLIST_KEY_UIBackgroundModes: audio
        # Full screen
        INFOPLIST_KEY_UIRequiresFullScreen: true
        INFOPLIST_KEY_UIStatusBarHidden: true
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          SWIFT_COMPILATION_MODE: wholemodule
    dependencies: []
    preBuildScripts: []
    scheme:
      testTargets: []
      gatherCoverageData: false
      commandLineArguments: {}

schemes:
  osu-droid:
    build:
      targets:
        osu-droid: all
    run:
      config: Debug
    archive:
      config: Release
